# Generated by Django 4.0.4 on 2022-04-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_education_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='track',
        ),
    ]
