# Generated by Django 4.0.4 on 2022-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_management_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
