# Generated by Django 4.0.4 on 2022-04-18 14:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_programming_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
