# Generated by Django 4.0.4 on 2022-04-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_programming_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
